---
development:
  cloud_name: de3vnm3hk
  api_key: '456146893178241'
  api_secret: qYg_NaLjHcBHGYM7zAMXIw2HY0A
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: de3vnm3hk
  api_key: '456146893178241'
  api_secret: qYg_NaLjHcBHGYM7zAMXIw2HY0A
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: de3vnm3hk
  api_key: '456146893178241'
  api_secret: qYg_NaLjHcBHGYM7zAMXIw2HY0A
  enhance_image_tag: true
  static_file_support: false
